export const INITIAL_USERS = [
  {
    id: 'usr-admin-1',
    employee_id: 'EMP-1001',
    full_name: 'Vikramaditya Sharma',
    email: 'admin@corporate.com',
    role: 'ADMIN',
    department_id: 'dept-it',
    department_name: 'Information Technology',
    designation: 'System Administrator',
    mobile: '+91 98765 43210',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    is_active: true,
  },
  {
    id: 'usr-manager-1',
    employee_id: 'EMP-1002',
    full_name: 'Ananya Roy',
    email: 'manager@corporate.com',
    role: 'MANAGER',
    department_id: 'dept-ops',
    department_name: 'Operations',
    designation: 'Operations Manager',
    mobile: '+91 98765 43211',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    is_active: true,
  },
  {
    id: 'usr-emp-1',
    employee_id: 'EMP-1003',
    full_name: 'Rahul Verma',
    email: 'employee@corporate.com',
    role: 'EMPLOYEE',
    department_id: 'dept-ops',
    department_name: 'Operations',
    designation: 'Operations Associate',
    mobile: '+91 98765 43212',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    is_active: true,
  },
  {
    id: 'usr-emp-2',
    employee_id: 'EMP-1004',
    full_name: 'Priya Sharma',
    email: 'priya@corporate.com',
    role: 'EMPLOYEE',
    department_id: 'dept-sales',
    department_name: 'Sales & Marketing',
    designation: 'Sales Executive',
    mobile: '+91 98765 43213',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    is_active: true,
  },
  {
    id: 'usr-emp-3',
    employee_id: 'EMP-1005',
    full_name: 'Siddharth Mehta',
    email: 'siddharth@corporate.com',
    role: 'EMPLOYEE',
    department_id: 'dept-accounts',
    department_name: 'Accounts & Finance',
    designation: 'Accounts Officer',
    mobile: '+91 98765 43214',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    is_active: true,
  }
];

export const INITIAL_CHECKLISTS = [
  {
    id: 'chk-101',
    checklist_code: 'CHK-DAILY-01',
    title: 'Daily Office Opening & System Check',
    description: 'Ensure premises opening, system boot-up, cleanliness, and security checks.',
    department_id: 'dept-ops',
    department_name: 'Operations',
    assigned_by: 'usr-manager-1',
    assigned_by_name: 'Ananya Roy',
    assigned_to: 'usr-emp-1',
    assigned_to_name: 'Rahul Verma',
    priority: 'High',
    frequency: 'Daily',
    start_date: '2026-09-01',
    end_date: '2026-12-31',
    reminder_status: true,
    is_active: true,
    items: [
      { id: 'item-1', item_title: 'Unlock main entrance and disable security alarm', order_index: 1, is_required: true },
      { id: 'item-2', item_title: 'Verify HVAC and ventilation systems operation', order_index: 2, is_required: true },
      { id: 'item-3', item_title: 'Boot up main server room routers & switches', order_index: 3, is_required: true },
      { id: 'item-4', item_title: 'Check pantry cleanliness and water dispensers', order_index: 4, is_required: true },
      { id: 'item-5', item_title: 'Verify employee biometrics attendance scanner online', order_index: 5, is_required: true },
    ]
  },
  {
    id: 'chk-102',
    checklist_code: 'CHK-WEEK-02',
    title: 'Weekly IT Security & Backup Verification',
    description: 'Perform off-site data backup verification and server health audit.',
    department_id: 'dept-it',
    department_name: 'Information Technology',
    assigned_by: 'usr-admin-1',
    assigned_by_name: 'Vikramaditya Sharma',
    assigned_to: 'usr-emp-1',
    assigned_to_name: 'Rahul Verma',
    priority: 'Critical',
    frequency: 'Weekly',
    start_date: '2026-09-01',
    end_date: '2026-12-31',
    reminder_status: true,
    is_active: true,
    items: [
      { id: 'item-21', item_title: 'Run database snapshot verification script', order_index: 1, is_required: true },
      { id: 'item-22', item_title: 'Verify SSL certificate expiry dates', order_index: 2, is_required: true },
      { id: 'item-23', item_title: 'Check firewall intrusion prevention logs', order_index: 3, is_required: true },
    ]
  }
];

export const INITIAL_TASKS = [
  {
    id: 'task-inst-1',
    type: 'checklist',
    task_code: 'TSK-CHK-1001',
    checklist_id: 'chk-101',
    title: 'Daily Office Opening Checklist - 13 Sep',
    description: 'Execute morning operational checklist for 13 September 2026.',
    department_id: 'dept-ops',
    department_name: 'Operations',
    assigned_by: 'usr-manager-1',
    assigned_by_name: 'Ananya Roy',
    assigned_to: 'usr-emp-1',
    assigned_to_name: 'Rahul Verma',
    priority: 'High',
    start_date: '2026-09-13',
    due_date: '2026-09-13T10:00:00.000Z',
    original_due_date: '2026-09-13T10:00:00.000Z',
    status: 'Pending',
    completion_date: null,
    completion_remarks: '',
    items: [
      { id: 'i1', title: 'Unlock main entrance and disable alarm', completed: false },
      { id: 'i2', title: 'Verify HVAC and ventilation systems operation', completed: false },
      { id: 'i3', title: 'Boot up main server room routers & switches', completed: false },
    ],
    created_at: '2026-09-13T06:00:00.000Z',
  },
  {
    id: 'task-inst-2',
    type: 'checklist',
    task_code: 'TSK-CHK-1000',
    checklist_id: 'chk-101',
    title: 'Daily Office Opening Checklist - 12 Sep',
    description: 'Execute morning operational checklist for 12 September 2026.',
    department_id: 'dept-ops',
    department_name: 'Operations',
    assigned_by: 'usr-manager-1',
    assigned_by_name: 'Ananya Roy',
    assigned_to: 'usr-emp-1',
    assigned_to_name: 'Rahul Verma',
    priority: 'High',
    start_date: '2026-09-12',
    due_date: '2026-09-12T10:00:00.000Z',
    original_due_date: '2026-09-12T10:00:00.000Z',
    status: 'Completed',
    completion_date: '2026-09-12T09:45:00.000Z',
    completion_remarks: 'All items verified cleanly. System online.',
    proof_image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400',
    items: [
      { id: 'i1', title: 'Unlock main entrance and disable alarm', completed: true },
      { id: 'i2', title: 'Verify HVAC and ventilation systems operation', completed: true },
    ],
    created_at: '2026-09-12T06:00:00.000Z',
  },
  {
    id: 'del-201',
    type: 'delegation',
    task_code: 'DEL-2026-001',
    title: 'Prepare Q3 Monthly Sales Performance Analysis Report',
    description: 'Compile region-wise sales data, revenue breakdown, and growth projections for board presentation.',
    department_id: 'dept-sales',
    department_name: 'Sales & Marketing',
    assigned_by: 'usr-manager-1',
    assigned_by_name: 'Ananya Roy',
    assigned_to: 'usr-emp-2',
    assigned_to_name: 'Priya Sharma',
    priority: 'High',
    start_date: '2026-09-05',
    due_date: '2026-09-15T18:00:00.000Z',
    original_due_date: '2026-09-15T18:00:00.000Z',
    status: 'In Progress',
    completion_date: null,
    completion_remarks: '',
    attachment_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    created_at: '2026-09-05T09:00:00.000Z',
  },
  {
    id: 'del-202',
    type: 'delegation',
    task_code: 'DEL-2026-002',
    title: 'Vendor Invoice Reconciliation & GST Audit',
    description: 'Reconcile Q2 vendor invoices against purchase orders and verify GST Input Tax Credit claims.',
    department_id: 'dept-accounts',
    department_name: 'Accounts & Finance',
    assigned_by: 'usr-admin-1',
    assigned_by_name: 'Vikramaditya Sharma',
    assigned_to: 'usr-emp-3',
    assigned_to_name: 'Siddharth Mehta',
    priority: 'Critical',
    start_date: '2026-09-01',
    due_date: '2026-09-10T17:00:00.000Z',
    original_due_date: '2026-09-10T17:00:00.000Z',
    status: 'Overdue',
    completion_date: null,
    completion_remarks: '',
    created_at: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'del-203',
    type: 'delegation',
    task_code: 'DEL-2026-003',
    title: 'Employee Workstation Hardware Upgrades',
    description: 'Upgrade RAM and SSDs for 15 workstations in the Design & Operations department.',
    department_id: 'dept-it',
    department_name: 'Information Technology',
    assigned_by: 'usr-manager-1',
    assigned_by_name: 'Ananya Roy',
    assigned_to: 'usr-emp-1',
    assigned_to_name: 'Rahul Verma',
    priority: 'Medium',
    start_date: '2026-09-08',
    due_date: '2026-09-14T17:00:00.000Z',
    original_due_date: '2026-09-12T17:00:00.000Z',
    status: 'In Progress',
    completion_date: null,
    created_at: '2026-09-08T11:00:00.000Z',
  }
];

export const INITIAL_EXTENSIONS = [
  {
    id: 'ext-301',
    task_id: 'del-203',
    task_code: 'DEL-2026-003',
    task_title: 'Employee Workstation Hardware Upgrades',
    requested_by: 'usr-emp-1',
    requested_by_name: 'Rahul Verma',
    current_due_date: '2026-09-12T17:00:00.000Z',
    requested_due_date: '2026-09-14T17:00:00.000Z',
    reason: 'Vendor delayed RAM module shipment by 2 business days.',
    status: 'Approved',
    reviewed_by: 'usr-manager-1',
    reviewed_by_name: 'Ananya Roy',
    reviewed_at: '2026-09-11T14:30:00.000Z',
    review_remarks: 'Approved due to documented vendor delay.',
    created_at: '2026-09-11T10:00:00.000Z',
  }
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-1',
    user_id: 'usr-emp-1',
    title: 'New Delegation Assigned',
    message: 'Ananya Roy assigned you "Employee Workstation Hardware Upgrades"',
    type: 'task_assigned',
    link_url: '/tasks',
    is_read: false,
    created_at: '2026-09-13T09:15:00.000Z'
  },
  {
    id: 'notif-2',
    user_id: 'usr-manager-1',
    title: 'Extension Request Approved',
    message: 'You approved Rahul Verma\'s extension request for DEL-2026-003',
    type: 'extension_approved',
    link_url: '/tasks',
    is_read: true,
    created_at: '2026-09-11T14:30:00.000Z'
  }
];

export const INITIAL_HISTORY = [
  {
    id: 'hist-1',
    task_id: 'del-203',
    performed_by_name: 'Ananya Roy',
    action: 'Task Created',
    details: 'Delegation created with due date 12 Sep 2026',
    created_at: '2026-09-08T11:00:00.000Z'
  },
  {
    id: 'hist-2',
    task_id: 'del-203',
    performed_by_name: 'Rahul Verma',
    action: 'Extension Requested',
    details: 'Requested extension to 14 Sep 2026. Reason: Vendor shipment delay.',
    created_at: '2026-09-11T10:00:00.000Z'
  },
  {
    id: 'hist-3',
    task_id: 'del-203',
    performed_by_name: 'Ananya Roy',
    action: 'Extension Approved',
    details: 'Due date updated from 12 Sep 2026 to 14 Sep 2026.',
    created_at: '2026-09-11T14:30:00.000Z'
  }
];

export const INITIAL_SETTINGS = {
  company_name: 'Acme Corporate Corp',
  company_logo: '',
  date_format: 'dd/MM/yyyy',
  time_format: '12h',
  default_priority: 'Medium',
  default_reminder: '1 Day Before',
  require_remarks_on_not_done: true,
  require_proof_attachment: false,
  extension_approval_required: true,
  on_time_score: 100,
  late_deduction_per_day: 10,
  overdue_score: 0,
};
