import {
  CheckSquare,
  LayoutDashboard,
  Bell,
  ClipboardList,
  Calendar,
  PartyPopper,
  Sliders,
  Plane,
  TrendingUp,
  Briefcase,
  FileText,
  ShoppingBag,
  ShoppingCart,
  Package,
  Users,
  UserCheck,
  Target,
  Workflow,
  Truck,
  DollarSign,
  FileSpreadsheet,
  CheckCircle2,
  Users2,
  Boxes,
  FileCheck,
  Clock,
  Database,
  ShieldCheck,
  Building,
  Building2,
  PlusCircle,
  CreditCard,
  PackageCheck,
  Archive,
  Receipt,
  Navigation
} from 'lucide-react';

export const SYSTEMS_CONFIG = [
  {
    id: 'checklist',
    name: 'Checklist & Tasks',
    shortName: 'Checklist',
    badge: 'Core & Tasks',
    description: 'Task assignment, recurring checklists & daily operations',
    icon: CheckSquare,
    color: 'indigo',
    gradient: 'from-indigo-600 to-purple-600',
    bgLight: 'bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-400',
    border: 'border-indigo-200 dark:border-indigo-800',
    defaultPath: '/dashboard',
    navItems: [
      { label: 'Dashboard', path: '/dashboard', icon: LayoutDashboard },
      { label: 'My Task', path: '/my-tasks', icon: CheckSquare },
      { label: 'Task Assignment', path: '/task-assignment', icon: ClipboardList, requiresSelfAssignOrManager: true },
      { label: 'Notification', path: '/notifications', icon: Bell },
      { label: 'Calendar', path: '/calendar', icon: Calendar },
      { label: 'Holiday', path: '/holidays', icon: PartyPopper },
      { label: 'Masters', path: '/masters', icon: Sliders, adminOnly: true },
    ]
  },
  {
    id: 'sales',
    name: 'Order To Delivery',
    shortName: 'Order To Delivery',
    badge: 'Revenue & CRM',
    description: 'Leads, Quotations, Sales Orders & Customer Relations',
    icon: TrendingUp,
    color: 'emerald',
    gradient: 'from-emerald-500 to-teal-600',
    bgLight: 'bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400',
    border: 'border-emerald-200 dark:border-emerald-800',
    defaultPath: '/sales/dashboard',
    navItems: [
      { label: 'Dashboard', path: '/sales/dashboard', icon: LayoutDashboard },
      { label: 'New Order', path: '/sales/new-order', icon: PlusCircle },
      { label: 'Order Verification', path: '/sales/verification', icon: ShieldCheck },
      { label: 'Order Approval', path: '/sales/approval', icon: FileCheck },
      { label: 'Advance Payment', path: '/sales/advance-payment', icon: DollarSign },
      { label: 'Stock Check', path: '/sales/stock-check', icon: Boxes },
      { label: 'Order Processing', path: '/sales/processing', icon: Workflow },
      { label: 'Quality Check (QC)', path: '/sales/qc', icon: CheckCircle2 },
      { label: 'Ready for Dispatch', path: '/sales/ready-dispatch', icon: PackageCheck },
      { label: 'Dispatch', path: '/sales/dispatch', icon: Truck },
      { label: 'Delivered', path: '/sales/delivered', icon: Package },
      { label: 'Payment Collection', path: '/sales/payment-collection', icon: CreditCard },
      { label: 'Order Closed', path: '/sales/closed', icon: Archive },
    ]
  },
  {
    id: 'master-system',
    name: 'Master System',
    shortName: 'Master System',
    badge: 'Core Masters',
    description: 'Centralized master data for Vendors, Products, Transporters, Users & TAT',
    icon: Sliders,
    color: 'rose',
    gradient: 'from-rose-500 to-pink-600',
    bgLight: 'bg-rose-50 dark:bg-rose-950/40 text-rose-600 dark:text-rose-400',
    border: 'border-rose-200 dark:border-rose-800',
    defaultPath: '/master-system/overview',
    navItems: [
      { label: 'Master Overview', path: '/master-system/overview', icon: LayoutDashboard },
      { label: 'Our Company Details', path: '/master-system/company-details', icon: Building2 },
      { label: 'Vendors Master', path: '/master-system/vendors', icon: Users2 },
      { label: 'Product Master', path: '/master-system/products', icon: Package },
      { label: 'Department Master', path: '/master-system/departments', icon: Building },
      { label: 'User / Employee Master', path: '/master-system/users', icon: UserCheck },
      { label: 'TAT Management', path: '/master-system/tat', icon: Clock },
      { label: 'Holidays Master', path: '/master-system/holidays', icon: Calendar },
    ]
  },
  {
    id: 'purchase',
    name: 'Purchase System',
    shortName: 'Purchase',
    badge: 'Procurement',
    description: 'Purchase indents, PO issuance, lifting, delivery, QC, GRN & payments',
    icon: ShoppingCart,
    color: 'amber',
    gradient: 'from-amber-500 to-orange-600',
    bgLight: 'bg-amber-50 dark:bg-amber-950/40 text-amber-600 dark:text-amber-400',
    border: 'border-amber-200 dark:border-amber-800',
    defaultPath: '/purchase/indent',
    navItems: [
      { label: 'Purchase Indent', path: '/purchase/indent', icon: FileText },
      { label: 'Indent Approval', path: '/purchase/indent-approval', icon: CheckSquare },
      { label: 'PO', path: '/purchase/po', icon: FileSpreadsheet },
      { label: 'Material Lifting / Dispatch', path: '/purchase/lifting-dispatch', icon: Truck },
      { label: 'Material Delivery', path: '/purchase/delivery', icon: Navigation },
      { label: 'Material Receiving', path: '/purchase/receiving', icon: PackageCheck },
      { label: 'Quality Check', path: '/purchase/qc', icon: ShieldCheck },
      { label: 'GRN', path: '/purchase/grn', icon: Receipt },
      { label: 'Payment', path: '/purchase/payment', icon: CreditCard },
    ]
  },
  {
    id: 'lead-to-orders',
    name: 'Lead To Orders',
    shortName: 'Lead-To-Order',
    badge: 'Pipeline & Deals',
    description: 'End-to-end lead qualification to order conversion pipeline',
    icon: Target,
    color: 'violet',
    gradient: 'from-violet-600 to-purple-600',
    bgLight: 'bg-violet-50 dark:bg-violet-950/40 text-violet-600 dark:text-violet-400',
    border: 'border-violet-200 dark:border-violet-800',
    defaultPath: '/lead-to-orders/pipeline',
    navItems: [
      { label: 'Lead Pipeline', path: '/lead-to-orders/pipeline', icon: Workflow },
      { label: 'Active Deals', path: '/lead-to-orders/deals', icon: Target },
      { label: 'Order Conversions', path: '/lead-to-orders/conversions', icon: CheckCircle2 },
    ]
  },
  {
    id: 'hr',
    name: 'HR System',
    shortName: 'HR & People',
    badge: 'Human Resources',
    description: 'Employee Directory, Leave Management, Attendance & Payroll',
    icon: Users,
    color: 'cyan',
    gradient: 'from-cyan-500 to-blue-600',
    bgLight: 'bg-cyan-50 dark:bg-cyan-950/40 text-cyan-600 dark:text-cyan-400',
    border: 'border-cyan-200 dark:border-cyan-800',
    defaultPath: '/hr/dashboard',
    navItems: [
      { label: 'HR Dashboard', path: '/hr/dashboard', icon: LayoutDashboard },
      { label: 'Employee Directory', path: '/hr/employees', icon: Users },
      { label: 'Leave Requests', path: '/leave-requests', icon: Plane },
      { label: 'Attendance Log', path: '/hr/attendance', icon: UserCheck },
      { label: 'Payroll & Docs', path: '/hr/payroll', icon: DollarSign },
    ]
  }
];
